/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewImportedRouteImport } from './routes/preview/imported'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiUploadthingFilesRouteImport } from './routes/api/uploadthing/files'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewImportedRoute = PreviewImportedRouteImport.update({
  id: '/preview/imported',
  path: '/preview/imported',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingFilesRoute = ApiUploadthingFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ApiUploadthingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/uploadthing': typeof ApiUploadthingRouteWithChildren
  '/preview/imported': typeof PreviewImportedRoute
  '/api/uploadthing/files': typeof ApiUploadthingFilesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/uploadthing': typeof ApiUploadthingRouteWithChildren
  '/preview/imported': typeof PreviewImportedRoute
  '/api/uploadthing/files': typeof ApiUploadthingFilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/uploadthing': typeof ApiUploadthingRouteWithChildren
  '/preview/imported': typeof PreviewImportedRoute
  '/api/uploadthing/files': typeof ApiUploadthingFilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/uploadthing'
    | '/preview/imported'
    | '/api/uploadthing/files'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/uploadthing' | '/preview/imported' | '/api/uploadthing/files'
  id:
    | '__root__'
    | '/'
    | '/api/uploadthing'
    | '/preview/imported'
    | '/api/uploadthing/files'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiUploadthingRoute: typeof ApiUploadthingRouteWithChildren
  PreviewImportedRoute: typeof PreviewImportedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/imported': {
      id: '/preview/imported'
      path: '/preview/imported'
      fullPath: '/preview/imported'
      preLoaderRoute: typeof PreviewImportedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing/files': {
      id: '/api/uploadthing/files'
      path: '/files'
      fullPath: '/api/uploadthing/files'
      preLoaderRoute: typeof ApiUploadthingFilesRouteImport
      parentRoute: typeof ApiUploadthingRoute
    }
  }
}

interface ApiUploadthingRouteChildren {
  ApiUploadthingFilesRoute: typeof ApiUploadthingFilesRoute
}

const ApiUploadthingRouteChildren: ApiUploadthingRouteChildren = {
  ApiUploadthingFilesRoute: ApiUploadthingFilesRoute,
}

const ApiUploadthingRouteWithChildren = ApiUploadthingRoute._addFileChildren(
  ApiUploadthingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiUploadthingRoute: ApiUploadthingRouteWithChildren,
  PreviewImportedRoute: PreviewImportedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
