/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRouteImport } from './routes/[__sprite-editor__]/sprites[.]json'
import { Route as Char91__spriteEditor__Char93SpritesSplatRouteImport } from './routes/[__sprite-editor__]/sprites/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRoute =
  Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRouteImport.update({
    id: '/__sprite-editor__/sprites.json',
    path: '/__sprite-editor__/sprites.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__spriteEditor__Char93SpritesSplatRoute =
  Char91__spriteEditor__Char93SpritesSplatRouteImport.update({
    id: '/__sprite-editor__/sprites/$',
    path: '/__sprite-editor__/sprites/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/__sprite-editor__/sprites.json': typeof Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRoute
  '/__sprite-editor__/sprites/$': typeof Char91__spriteEditor__Char93SpritesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/__sprite-editor__/sprites.json': typeof Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRoute
  '/__sprite-editor__/sprites/$': typeof Char91__spriteEditor__Char93SpritesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__sprite-editor__/sprites.json': typeof Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRoute
  '/__sprite-editor__/sprites/$': typeof Char91__spriteEditor__Char93SpritesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/__sprite-editor__/sprites.json'
    | '/__sprite-editor__/sprites/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/__sprite-editor__/sprites.json' | '/__sprite-editor__/sprites/$'
  id:
    | '__root__'
    | '/'
    | '/__sprite-editor__/sprites.json'
    | '/__sprite-editor__/sprites/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRoute: typeof Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRoute
  Char91__spriteEditor__Char93SpritesSplatRoute: typeof Char91__spriteEditor__Char93SpritesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__sprite-editor__/sprites.json': {
      id: '/__sprite-editor__/sprites.json'
      path: '/__sprite-editor__/sprites.json'
      fullPath: '/__sprite-editor__/sprites.json'
      preLoaderRoute: typeof Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__sprite-editor__/sprites/$': {
      id: '/__sprite-editor__/sprites/$'
      path: '/__sprite-editor__/sprites/$'
      fullPath: '/__sprite-editor__/sprites/$'
      preLoaderRoute: typeof Char91__spriteEditor__Char93SpritesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRoute:
    Char91__spriteEditor__Char93SpritesChar91DotChar93jsonRoute,
  Char91__spriteEditor__Char93SpritesSplatRoute:
    Char91__spriteEditor__Char93SpritesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
